name: Bitcoin Data Collector

on:
  schedule:
  - cron: '*/5 * * * *' # This triggers the workflow every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pandas pandas_ta
          pip install git+https://github.com/rongardF/tvdatafeed.git

      - name: Run Bitcoin Script
        run: python collect_bitcoin.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/bitcoin.json
          if git diff --staged --quiet; then
            echo "No BTC changes to commit"
          else
            git commit -m "Bitcoin Pattern Update: $(date)"
            git push origin main
          fi
